server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/meal?serverTimezone=Asia/Seoul # port ?? ??
    username: root # ????
    password: 123456 #????

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create  # create update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  #  sql:
  #    init:
  #      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:


          naver:
            clientId:
            clientSecret:
            scope:

            clientName:
            authorizationGrantType:
            redirectUri:

          kakao:
            clientId:
            scope:
            clientName:
            authorizationGrantType:
            clientAuthenticationMethod:
            redirectUri:

        provider:
          naver:
            authorizationUri:
            tokenUri:
            userInfoUri:
            userNameAttribute:

          kakao:
            authorizationUri:
            tokenUri:
            userInfoUri:
            userNameAttribute:
